#### Steps in this notebook
- Clean Cricsheet data, create basic model
- Run basic model for testing

In [141]:
import pandas as pd
import numpy as np
import math

In [16]:
cricsheet_df=pd.read_csv('./data/all_matches.csv')

/Users/kishan/Desktop/IPL/.ipl/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [52]:
###Load input format dataframe

test_df=pd.read_csv('./submission/inputFile.csv')

test_df

##Venue needs to go through standardizer
## innigns is either 1 or 2
## Batting team and bowling team better to go through standardizer, since KXIP has changed names between seasons
## Batsmen list must be minimum 2 and bowlers list must be minimum 2
## Need to standardize batter and bowlers
## Batting and bowling types of batters and bowlers to be inferred from custom module

,venue,innings,batting_team,bowling_team,batsmen,bowlers
0,MA Chidambaram Stadium,1,Mumbai Indians,Kolkata Knight Riders,"Quinton de Kock, Rohit Sharma, Suryakumar Yadav","Harbhajan Singh, Varun Chakravarthy, Shakib Al..."

#### Subsetting the given data

- Remove seasons before 2018
- Remove super over innings (innings>=3)
- Remove unnecessary columns

In [17]:
##no use of other wicket type and other player dismissed columns
assert cricsheet_df.loc[~pd.isnull(cricsheet_df['other_wicket_type'])].shape[0]==0
assert cricsheet_df.loc[~pd.isnull(cricsheet_df['other_player_dismissed'])].shape[0]==0

In [28]:
cricsheet_df.drop(columns=['other_wicket_type','other_player_dismissed'],axis=1,inplace=True)

In [29]:
cricsheet_df['start_date']=pd.to_datetime(cricsheet_df['start_date'])

In [30]:
##Filter from 2018 April 7th
cricsheet_df.loc[cricsheet_df['start_date']>='2018','start_date'].describe(include='all')

<ipython-input-30-ff7ecb1db089>:2: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  cricsheet_df.loc[cricsheet_df['start_date']>='2018','start_date'].describe(include='all')

count                   43894
unique                    149
top       2020-10-18 00:00:00
freq                      520
first     2018-04-07 00:00:00
last      2021-04-11 00:00:00
Name: start_date, dtype: object

In [124]:
cdf=cricsheet_df.loc[cricsheet_df['start_date']>='2018'].reset_index(drop=True)

### EDA

In [125]:
##List of all venues in this
set(cdf['venue'])

{'Arun Jaitley Stadium',
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
 'Dubai International Cricket Stadium',
 'Eden Gardens',
 'Holkar Cricket Stadium',
 'M.Chinnaswamy Stadium',
 'MA Chidambaram Stadium',
 'MA Chidambaram Stadium, Chepauk, Chennai',
 'Maharashtra Cricket Association Stadium',
 'Punjab Cricket Association IS Bindra Stadium',
 'Rajiv Gandhi International Stadium',
 'Sawai Mansingh Stadium',
 'Sharjah Cricket Stadium',
 'Sheikh Zayed Stadium',
 'Wankhede Stadium',
 'Wankhede Stadium, Mumbai'}

#### There are 231 different IPL players across teams from 2018.

In [126]:
##List of all unique players in the dataset
ipl_players=cdf.loc[:,['striker','non_striker','bowler']].drop_duplicates().melt()['value'].drop_duplicates().tolist()

len(ipl_players),ipl_players

(231,
 ['V Kohli',
  'PA Patel',
  'MM Ali',
  'AB de Villiers',
  'SO Hetmyer',
  'S Dube',
  'C de Grandhomme',
  'NA Saini',
  'YS Chahal',
  'UT Yadav',
  'Mohammed Siraj',
  'SR Watson',
  'AT Rayudu',
  'SK Raina',
  'KM Jadhav',
  'RA Jadeja',
  'DA Warner',
  'JM Bairstow',
  'V Shankar',
  'YK Pathan',
  'MK Pandey',
  'CA Lynn',
  'N Rana',
  'RV Uthappa',
  'KD Karthik',
  'AD Russell',
  'Shubman Gill',
  'PP Shaw',
  'S Dhawan',
  'SS Iyer',
  'CA Ingram',
  'RR Pant',
  'KMA Paul',
  'AR Patel',
  'R Tewatia',
  'RG Sharma',
  'Q de Kock',
  'SA Yadav',
  'KA Pollard',
  'Yuvraj Singh',
  'HH Pandya',
  'KH Pandya',
  'BCJ Cutting',
  'MJ McClenaghan',
  'Rasikh Salam',
  'KL Rahul',
  'MA Agarwal',
  'CH Gayle',
  'SN Khan',
  'N Pooran',
  'Mandeep Singh',
  'AM Rahane',
  'JC Buttler',
  'SV Samson',
  'SPD Smith',
  'RA Tripathi',
  'BA Stokes',
  'K Gowtham',
  'JC Archer',
  'JD Unadkat',
  'S Gopal',
  'DS Kulkarni',
  'MS Dhoni',
  'DJ Bravo',
  'SP Narine',
  'DA Miller',
  'M Markande',
  'JJ Bumrah',
  'KS Williamson',
  'Rashid Khan',
  'NS Naik',
  'PP Chawla',
  'Kuldeep Yadav',
  'GH Vihari',
  'P Ray Barman',
  'SM Curran',
  'GC Viljoen',
  'R Ashwin',
  'M Ashwin',
  'Mohammed Shami',
  'CH Morris',
  'HV Patel',
  'Avesh Khan',
  'K Rabada',
  'S Lamichhane',
  'MP Stoinis',
  'DL Chahar',
  'SN Thakur',
  'MM Sharma',
  'DJ Hooda',
  'Mohammad Nabi',
  'F du Plessis',
  'Ishan Kishan',
  'RD Chahar',
  'B Kumar',
  'Sandeep Sharma',
  'S Kaul',
  'AD Nath',
  'TG Southee',
  'P Negi',
  'M Prasidh Krishna',
  'HF Gurney',
  'KK Nair',
  'SD Lad',
  'AS Joseph',
  'R Parag',
  'MJ Santner',
  'JL Denly',
  'CR Brathwaite',
  'LS Livingstone',
  'C Munro',
  'RK Bhui',
  'Abhishek Sharma',
  'KK Ahmed',
  'Mujeeb Ur Rahman',
  'AJ Turner',
  'STR Binny',
  'SW Billings',
  'E Lewis',
  'Harbhajan Singh',
  'MA Wood',
  'Imran Tahir',
  'G Gambhir',
  'DT Christian',
  'BB McCullum',
  'CR Woakes',
  'RK Singh',
  'R Vinay Kumar',
  'DJM Short',
  'B Laughlin',
  'WP Saha',
  'TK Curran',
  'GJ Maxwell',
  'PJ Sangwan',
  'Shakib Al Hasan',
  'B Stanlake',
  'AJ Finch',
  'AJ Tye',
  'Washington Sundar',
  'A Dananjaya',
  'JJ Roy',
  'Shivam Mavi',
  'MG Johnson',
  'M Vijay',
  'S Nadeem',
  'TA Boult',
  'CJ Anderson',
  'H Klaasen',
  'M Vohra',
  'BB Sran',
  'LE Plunkett',
  'A Mishra',
  'Basil Thampi',
  'Mustafizur Rahman',
  'MK Tiwary',
  'AS Rajpoot',
  'AD Hales',
  'MK Lomror',
  'JP Duminy',
  'DR Shorey',
  'NV Ojha',
  'P Chopra',
  'JPR Scantlebury-Searles',
  'IS Sodhi',
  'Anureet Singh',
  'SP Goswami',
  'Harpreet Brar',
  'SE Rutherford',
  'Y Prithvi Raj',
  'KC Cariappa',
  'Gurkeerat Singh',
  'P Simran Singh',
  'J Suchith',
  'MJ Guptill',
  'VR Aaron',
  'I Sharma',
  'SS Tiwary',
  'JL Pattinson',
  'A Nortje',
  'CJ Jordan',
  'D Padikkal',
  'JR Philippe',
  'PK Garg',
  'MR Marsh',
  'T Natarajan',
  'YBK Jaiswal',
  'RD Gaikwad',
  'EJG Morgan',
  'PJ Cummins',
  'DW Steyn',
  'KL Nagarkoti',
  'Abdul Samad',
  'JDS Neesham',
  'Ravi Bishnoi',
  'I Udana',
  'CV Varun',
  'SS Cottrell',
  'Arshdeep Singh',
  'Kartik Tyagi',
  'N Jagadeesan',
  'AT Carey',
  'T Banton',
  'NM Coulter-Nile',
  'LH Ferguson',
  'TU Deshpande',
  'JO Holder',
  'Shahbaz Ahmed',
  'P Dubey',
  'DR Sams',
  'M Jansen',
  'RM Patidar',
  'KA Jamieson',
  'KV Sharma',
  'SL Malinga',
  'JP Behrendorff',
  'SC Kuggeleijn',
  'S Midhun',
  'K Khejroliya',
  'L Ngidi',
  'KM Asif',
  'DJ Willey',
  'Ankit Sharma',
  'CJ Dala',
  'J Yadav',
  'O Thomas',
  'AS Roy',
  'S Sandeep Warrier',
  'JR Hazlewood',
  'A Zampa',
  'CJ Green',
  'Monu Kumar'])

In [127]:
### Format seasons
print(set(cdf['season']))

cdf['season']=cdf['season'].astype('str')
print(set(cdf['season']))

{2018, 2019, '2019', '2018', '2020/21', '2021'}
{'2020/21', '2018', '2019', '2021'}

In [128]:
##Remove super overs and repeated super over instance from MI KXIP
cdf=cdf.loc[cdf['innings']<=2]

In [129]:
##Which venues need tweaking? For purposes of training
cdf['venue'].value_counts(ascending=False)

Dubai International Cricket Stadium                    6338
Sheikh Zayed Stadium                                   5294
Wankhede Stadium                                       3902
Eden Gardens                                           3802
Rajiv Gandhi International Stadium                     3609
Arun Jaitley Stadium                                   3344
Sawai Mansingh Stadium                                 3286
M.Chinnaswamy Stadium                                  3246
Sharjah Cricket Stadium                                2878
Punjab Cricket Association IS Bindra Stadium           2429
MA Chidambaram Stadium                                 2130
Maharashtra Cricket Association Stadium                1467
Holkar Cricket Stadium                                  873
MA Chidambaram Stadium, Chepauk, Chennai                498
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium     491
Wankhede Stadium, Mumbai                                239
Name: venue, dtype: int64

In [130]:
cdf.loc[cdf['venue']=='MA Chidambaram Stadium, Chepauk, Chennai','venue']='MA Chidambaram Stadium'
cdf.loc[cdf['venue']=='Wankhede Stadium, Mumbai','venue']='Wankhede Stadium'

In [131]:
cdf['venue'].value_counts(ascending=False)

Dubai International Cricket Stadium                    6338
Sheikh Zayed Stadium                                   5294
Wankhede Stadium                                       4141
Eden Gardens                                           3802
Rajiv Gandhi International Stadium                     3609
Arun Jaitley Stadium                                   3344
Sawai Mansingh Stadium                                 3286
M.Chinnaswamy Stadium                                  3246
Sharjah Cricket Stadium                                2878
MA Chidambaram Stadium                                 2628
Punjab Cricket Association IS Bindra Stadium           2429
Maharashtra Cricket Association Stadium                1467
Holkar Cricket Stadium                                  873
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium     491
Name: venue, dtype: int64

In [132]:
##List of all unique teams in the dataset
ipl_teams=cdf.loc[:,['batting_team','bowling_team']].drop_duplicates().melt()['value'].drop_duplicates().tolist()
ipl_teams
##Change Delhi Daredevils to Delhi Capitals
##Change Kings XI Punjab to Punjab Kings

['Royal Challengers Bangalore',
 'Chennai Super Kings',
 'Sunrisers Hyderabad',
 'Kolkata Knight Riders',
 'Delhi Capitals',
 'Mumbai Indians',
 'Kings XI Punjab',
 'Rajasthan Royals',
 'Delhi Daredevils']

In [133]:
cdf.loc[cdf['batting_team']=='Delhi Daredevils','batting_team']='Delhi Capitals'
cdf.loc[cdf['bowling_team']=='Delhi Daredevils','bowling_team']='Delhi Capitals'
cdf.loc[cdf['batting_team']=='Kings XI Punjab','batting_team']='Punjab Kings'
cdf.loc[cdf['bowling_team']=='Kings XI Punjab','bowling_team']='Punjab Kings'

In [134]:
##Changed teams list

cdf.loc[:,['batting_team','bowling_team']].drop_duplicates().melt()['value'].drop_duplicates().tolist()

['Royal Challengers Bangalore',
 'Chennai Super Kings',
 'Sunrisers Hyderabad',
 'Kolkata Knight Riders',
 'Delhi Capitals',
 'Mumbai Indians',
 'Punjab Kings',
 'Rajasthan Royals']

In [137]:
##Extras column has captured type of extras
##At test time we will not have ball by ball information, do we need to hold a split of extras in that case??
cdf.drop(columns=['wides','noballs','byes','legbyes','penalty'],inplace=True)

### Derive new features

In [139]:
cdf['total_runs']=cdf['runs_off_bat']+cdf['extras']

In [142]:
##Get over number
cdf['over_number']=cdf['ball'].apply(lambda x:int(math.ceil(x)))

In [143]:
def phase_cat(over_number):
    '''Determine phase'''
    if over_number<=6:
        phase="PowerPlay"
    if (over_number>6) & (over_number<=15):
        phase="Middle overs"
    if over_number>15:
        phase="Death overs"
    return phase

In [144]:
cdf['phase']=cdf['over_number'].apply(phase_cat)

In [146]:
cdf.to_csv('./data/cleaned_cricsheet.csv',index=False)

In [199]:
cdf.to_excel('./data/cleaned_cricsheet.xlsx',index=False)

### What features can we derive at test time


**Assuming that we can add data to lookup in the submission file**

#### Toss related factors
- Derive who is batting 1st and who is batting 2nd (by order of rows)
- Check team wise
- We will know what kind of game it is, if it is a DAY start or NIGHT start, so we can supply that manually into the submission code


#### Venue related factors
- Venue specific stats, avg PP score in last 'n' games batting 1st (through a lookup table)
- Venue specific stats, avg PP score in last 'n' games batting 2nd (through a lookup table)

#### Team related factors

- When team is batting 1st, what is the avg PP score
- When team is batting 2nd, what is the avg PP score


#### Batsman related factors

- Since the input is a set of all batters in the list, the order will matter. Assuming openers are 1st two, we can measure size of this set to determine number of wickets that have fallen

- We will not have split of how many balls each batter faced. Hence we need to be careful not to over use the batsman feature

- Lookup batter at venue in 1st innings

- Lookup batter at venue in 2nd innings

- One proxy could be to determine average batting time of batsman in PP by batting position at venue

#### Bowler related factors

- Again we dont have info on the split of balls bowled. 

- Lookup bowler at venue in 1st innings how many overs he has generally bowled * ER
 
- Lookup bowler at venue in 2nd innings how many overs he has generally bowled * ER at venue

#### Batsman-Bowler matchups

- Infer batting hand of Batsman, bowling type of bowlers

#### Handle unknowns

- Bowlers like Chetan Sakariya, Avesh Khan are bowling rarely or for the first time. Model must be robust enough to handle "Unknowns"

### Begin model training pipeline

In [229]:
game_start_type="Night"

In [225]:
##Venue related sums
venue_df=cdf.loc[cdf['phase']=='PowerPlay'].groupby(['venue','start_date','match_id','innings'])['total_runs','wicket_type'].agg({'total_runs':'sum','wicket_type':'count'}).reset_index()

<ipython-input-225-e63dc6b94306>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  venue_df=cdf.loc[cdf['phase']=='PowerPlay'].groupby(['venue','start_date','match_id','innings'])['total_runs','wicket_type'].agg({'total_runs':'sum','wicket_type':'count'}).reset_index()

In [227]:
venue_df.to_excel('./data/venue_df.xlsx',index=False)

### Powerplay specific features for 2018, 2019. Try to use it on 2021

In [202]:
match_df=cdf.loc[cdf['match_id']==1136565]

In [203]:
match_df

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wicket_type,player_dismissed,total_runs,over_number,phase
8950,1136565,2018,2018-04-10,MA Chidambaram Stadium,1,0.1,Kolkata Knight Riders,Chennai Super Kings,CA Lynn,SP Narine,DL Chahar,0,0,NaN,NaN,0,1,PowerPlay
8951,1136565,2018,2018-04-10,MA Chidambaram Stadium,1,0.2,Kolkata Knight Riders,Chennai Super Kings,CA Lynn,SP Narine,DL Chahar,4,0,NaN,NaN,4,1,PowerPlay
8952,1136565,2018,2018-04-10,MA Chidambaram Stadium,1,0.3,Kolkata Knight Riders,Chennai Super Kings,CA Lynn,SP Narine,DL Chahar,1,0,NaN,NaN,1,1,PowerPlay
8953,1136565,2018,2018-04-10,MA Chidambaram Stadium,1,0.4,Kolkata Knight Riders,Chennai Super Kings,SP Narine,CA Lynn,DL Chahar,0,1,NaN,NaN,1,1,PowerPlay
8954,1136565,2018,2018-04-10,MA Chidambaram Stadium,1,0.5,Kolkata Knight Riders,Chennai Super Kings,SP Narine,CA Lynn,DL Chahar,0,0,NaN,NaN,0,1,PowerPlay
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9191,1136565,2018,2018-04-10,MA Chidambaram Stadium,2,19.3,Chennai Super Kings,Kolkata Knight Riders,DJ Bravo,RA Jadeja,R Vinay Kumar,1,0,NaN,NaN,1,20,Death overs
9192,1136565,2018,2018-04-10,MA Chidambaram Stadium,2,19.4,Chennai Super Kings,Kolkata Knight Riders,RA Jadeja,DJ Bravo,R Vinay Kumar,0,1,NaN,NaN,1,20,Death overs
9193,1136565,2018,2018-04-10,MA Chidambaram Stadium,2,19.5,Chennai Super Kings,Kolkata Knight Riders,RA Jadeja,DJ Bravo,R Vinay Kumar,1,0,NaN,NaN,1,20,Death overs
9194,1136565,2018,2018-04-10,MA Chidambaram Stadium,2,19.6,Chennai Super Kings,Kolkata Knight Riders,DJ Bravo,RA Jadeja,R Vinay Kumar,1,0,NaN,NaN,1,20,Death overs
9195,1136565,2018,2018-04-10,MA Chidambaram Stadium,2,19.7,Chennai Super Kings,Kolkata Knight Riders,RA Jadeja,DJ Bravo,R Vinay Kumar,6,0,NaN,NaN,6,20,Death overs

In [180]:
pp_score1=int(match_df.loc[(match_df['phase']=='PowerPlay')&(match_df['innings']==1)]['total_runs'].sum())
pp_score2=int(match_df.loc[(match_df['phase']=='PowerPlay')&(match_df['innings']==2)]['total_runs'].sum())

In [187]:
pp_batters1=match_df.loc[(match_df['phase']=='PowerPlay')&(match_df['innings']==1),['striker','non_striker']].melt()['value'].drop_duplicates().tolist()
pp_batters1.sort()
pp_batters2=match_df.loc[(match_df['phase']=='PowerPlay')&(match_df['innings']==2),['striker','non_striker']].melt()['value'].drop_duplicates().tolist()
pp_batters2.sort()

In [188]:
pp_batters1, pp_batters2

(['AB de Villiers', 'MM Ali', 'PA Patel', 'V Kohli'],
 ['AT Rayudu', 'SK Raina', 'SR Watson'])

In [189]:
pp_bowlers1=match_df.loc[(match_df['phase']=='PowerPlay')&(match_df['innings']==1),['bowler']].melt()['value'].drop_duplicates().tolist()
pp_bowlers1.sort()


pp_bowlers2=match_df.loc[(match_df['phase']=='PowerPlay')&(match_df['innings']==2),['bowler']].melt()['value'].drop_duplicates().tolist()
pp_bowlers2.sort()

In [190]:
pp_bowlers1,pp_bowlers2

(['DL Chahar', 'Harbhajan Singh'], ['MM Ali', 'NA Saini', 'YS Chahal'])

In [191]:
match_df

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wicket_type,player_dismissed,total_runs,over_number,phase
0,1175356,2019,2019-03-23,MA Chidambaram Stadium,1,0.1,Royal Challengers Bangalore,Chennai Super Kings,V Kohli,PA Patel,DL Chahar,1,0,NaN,NaN,1,1,PowerPlay
1,1175356,2019,2019-03-23,MA Chidambaram Stadium,1,0.2,Royal Challengers Bangalore,Chennai Super Kings,PA Patel,V Kohli,DL Chahar,0,0,NaN,NaN,0,1,PowerPlay
2,1175356,2019,2019-03-23,MA Chidambaram Stadium,1,0.3,Royal Challengers Bangalore,Chennai Super Kings,PA Patel,V Kohli,DL Chahar,0,0,NaN,NaN,0,1,PowerPlay
3,1175356,2019,2019-03-23,MA Chidambaram Stadium,1,0.4,Royal Challengers Bangalore,Chennai Super Kings,PA Patel,V Kohli,DL Chahar,0,0,NaN,NaN,0,1,PowerPlay
4,1175356,2019,2019-03-23,MA Chidambaram Stadium,1,0.5,Royal Challengers Bangalore,Chennai Super Kings,PA Patel,V Kohli,DL Chahar,4,0,NaN,NaN,4,1,PowerPlay
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,1175356,2019,2019-03-23,MA Chidambaram Stadium,2,17.1,Chennai Super Kings,Royal Challengers Bangalore,KM Jadhav,RA Jadeja,S Dube,1,0,NaN,NaN,1,18,Death overs
210,1175356,2019,2019-03-23,MA Chidambaram Stadium,2,17.2,Chennai Super Kings,Royal Challengers Bangalore,RA Jadeja,KM Jadhav,S Dube,0,1,NaN,NaN,1,18,Death overs
211,1175356,2019,2019-03-23,MA Chidambaram Stadium,2,17.3,Chennai Super Kings,Royal Challengers Bangalore,RA Jadeja,KM Jadhav,S Dube,0,0,NaN,NaN,0,18,Death overs
212,1175356,2019,2019-03-23,MA Chidambaram Stadium,2,17.4,Chennai Super Kings,Royal Challengers Bangalore,RA Jadeja,KM Jadhav,S Dube,0,0,NaN,NaN,0,18,Death overs
213,1175356,2019,2019-03-23,MA Chidambaram Stadium,2,17.5,Chennai Super Kings,Royal Challengers Bangalore,RA Jadeja,KM Jadhav,S Dube,1,0,NaN,NaN,1,18,Death overs